services:
  rabbitmq:
    image: rabbitmq:4.0.2-management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"
    expose:
      - "5672"
    volumes:
      - ./docker-conf/rabbitmq/data/:/var/lib/rabbitmq
      - ./docker-conf/rabbitmq/log/:/var/log/rabbitmq
      - ./docker-conf/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
    environment:
      - RABBITMQ_DEFAULT_USER=crawler
      - RABBITMQ_DEFAULT_PASS=rabbit
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - network_project

  worker:
    build:
      context: ./src/worker
      dockerfile: Dockerfile
    image: scrap_sintegra_worker
    container_name: worker
    ports:
      - "8080:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: crawler
      RABBITMQ_PASS: rabbit
    networks:
      - network_project

  api:
    build:
      context: ./src/app
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./src/app:/usr/src/app
    networks:
      - network_project
    depends_on:
      - rabbitmq
      - redis

  redis:
    image: redis:7.4.1-alpine
    container_name: redis
    ports:
      - '6380:6379'
    volumes:
      - ./docker-conf/redis/data:/data
      - ./docker-conf/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: redis-server /usr/local/etc/redis/redis.conf --save 20 1 --loglevel warning
    
networks:
  network_project:
    driver: bridge
