[supervisord]
nodaemon=true

[program:sintegra_goias]
process_name=%(program_name)s-%(process_num)02d
numprocs=2
command=python -m sintegra_goias.consumer_sintegra_goias
directory=/usr/src/app
environment=PYTHONPATH="/usr/src/app"
autostart=true
autorestart=true
startretries=15

stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
